- set_fact:
    technique: "{{ item.technique }}"
    atomic_test_guid: "{{ item.guid | default('') }}"
    ar_atomic_red_team_ansible_execution_timeout: "{{ (ar_atomic_red_team_timeout_seconds | int) + (ar_atomic_red_team_ansible_timeout_buffer_seconds | int) }}"

- debug:
    var: technique

- name: Get requirements for Atomic Red Team Technique
  win_shell: |
    Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
    Invoke-AtomicTest "{{ technique }}"{% if atomic_test_guid | length > 0 %} -TestGuids "{{ atomic_test_guid }}"{% endif %} -GetPrereqs
  register: requirements
  ignore_errors: True
  timeout: 600

- block:
  - name: Run specified Atomic Red Team Technique
    win_shell: |
      Set-ExecutionPolicy bypass
      Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
      Invoke-AtomicTest "{{ technique }}"{% if atomic_test_guid | length > 0 %} -TestGuids "{{ atomic_test_guid }}"{% endif %} -Confirm:$false -TimeoutSeconds {{ ar_atomic_red_team_timeout_seconds }} -ExecutionLogPath C:\AtomicRedTeam\atc_execution.csv
    register: output_art
    ignore_errors: True
    timeout: "{{ ar_atomic_red_team_ansible_execution_timeout }}"

  always:
  - name: Cleanup after execution
    win_shell: |
      Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
      Invoke-AtomicTest "{{ technique }}"{% if atomic_test_guid | length > 0 %} -TestGuids "{{ atomic_test_guid }}"{% endif %} -Cleanup
    register: cleanup
    timeout: 300

- debug:
    var: output_art.stdout_lines
